### ISSUE TITLE
teaspoon CLI exits with status 0 on syntax errors

### ISSUE THREAD

**Issue by rickmzp** [jejacks0n/teaspoon#154]
If there are syntax errors, the runner exits with status 0 when ideally it would exit with 1 so CI servers can stop the build (and email devs, etc.). Right now I have a syntax error in `spec/javascripts/spec_helper.js` and I get an output signaling a successful run with 0 examples, 0 falures.

I've investigated the code a little bit and haven't yet found a simple way to make this happen. Seems like it won't exit with a status of 1 unless there is at least 1 test failure, but it won't account for tests that couldn't run due to other issues.

Thanks!

**Comment by maxhudson** [comment]
@jejacks0n neither of these two snippets fix this problem when a tester makes the following type of syntax error:

```
describe('', function() {
  it('', function() {
    ({ //extraneous opening parens/braces
  });
});
```

Tests pass and this 'example' is not counted in the example totals.

Any brilliant ideas?

Max

**Comment by jejacks0n** [comment]
not really.. that on_error happens well after any parsing issues come up.. I don't recall exactly, but there's a weird convolution between sprockets handling errors in parsing, like for instance coffeescript or es6 parse errors, some gems that try and improve error reporting/exceptions -- combined with the browser layer of "this parsing exception happened long before any teaspoon javascript was parsed/executed". literally, that entire spec file won't execute.
