### ISSUE TITLE
Random Order Tests

### ISSUE THREAD

**Issue by baweaver** [jejacks0n/teaspoon#185]
Are there any methods to, or plans to implement features to make tests run in random order? If not, what would need to be done to implement such a feature?

**Comment by mleone** [comment]
Hey folks, I'd like to reopen this issue. It looks like Jasmine **has** supported random-order specs since 2015 ( see https://github.com/jasmine/jasmine/pull/927 ). How can I get my specs to run in random order via teaspoon?

**Comment by hidroo** [comment]
Hello, guys, I am on the same train here. Would like to run my tests in random order.
