### ISSUE TITLE
Test Suite hangs on Teapsoon 0.8.0

### ISSUE THREAD

**Issue by robotarmy** [jejacks0n/teaspoon#217]
Hi - our testsuite hangs with the new version of teaspoon-qunit

i've tried with qunit 12 and 14 and have the same issue - everything works  fine in teaspoon 0.7.9

I've  moved everything over  from teaspoon initializer to the env file almost exact - keeping the new stuff.

My test helper is the same except I had to convert it to javascript

I'm testing with ember and there is lots of async stuff going on so it's pretty hard to debug.

Just FYI!

**Comment by bramski** [comment]
Our test suite on 0.8.0 seems to hang a lot as well.
