### ISSUE TITLE
css dependent fixtures

### ISSUE THREAD

**Issue by brewster1134** [jejacks0n/teaspoon#223]
How would you apply styles to fixtures (aside from writing them inline)?  The JS library I am testing depends on some box-model related styles.  using a script tag in the fixture does not seem to work, seemingly because the fixtures are not added to the dom.

``` html
<style>
  div {
    width: 100px;
  }
</style>

<div>foo</div>
```

**Comment by eliotc1986** [comment]
@jejacks0n I'm having trouble including a fixture-specific stylesheet.

I have a file in spec/javascripts/stylesheets where I define the path to the stylesheet

how do you include a path to that fixture file in the xxx_spec.js file?

**Comment by brewster1134** [comment]
@eliotc1986 i created some helpers in my spec_helper

```coffee
window.loadJs = (file) ->
  $('head').append $('<script/>').attr('src', "/assets/#{file}.js")

window.loadCss = (file) ->
  $('head').prepend $('<link rel="stylesheet"/>').attr('href', "/assets/stylesheets/#{file}_spec.css")

window.loadHtml = (file) ->
  $('#fixture').html fixture.preload("#{file}_spec.html")[0]
  $('#fixture')
```

then in my specs...

```coffee
describe 'Modal', ->
  $modal = null

  before ->
    loadHtml 'foo_html_fixture'
    loadCss 'foo'
    loadJs 'release/core'
    loadJs 'release/foo'
```

this lets me load html fixtures, css, or js on demand as i need them in my spec.  the only thing i load in my spec_helper are globally shared assets.

maybe there is a more conventional way to do this though?

**Comment by jejacks0n** [comment]
Thanks @brewster1134!

That seems like a good way to use it -- the css fixtures were never fleshed out because it's not super common. It was mostly about providing a place to put them, and how they're used is primarily up to the test harness that you create to handle those sorts of things.

**Comment by brewster1134** [comment]
yeah i like to use css to set `transition-duration`s to 0 VS using fake timers or whatever.  also `loadHtml` returns the `#fixture` element so you can do stuff like...

```coffee
$bar = loadHtml('foo').find('#bar')
```

the `#fixture` element is loaded via teaspoon settings for `body_partial` in case anyone was wondering where that element was coming from.

**Comment by jejacks0n** [comment]
Thanks for the info. =) And yeah, I've mostly needed it for transition overrides as well, and in integration (cucumber features) showing elements that need to be "visible" to interact with.
