### ISSUE TITLE
How to run phantomjs on app in test environment?

### ISSUE THREAD

**Issue by aharpervc** [jejacks0n/teaspoon#255]
Is there a way to configure teaspoon to use the rails environment "test", but only when running via phantomjs? This would be similar to booting rails with `-e test`? By default, teaspoon appears to be using the "development" environment.

**Comment by sc0ttman** [comment]
Yea, I need this as well since `rack-mini-profiler` doesn't work nicely with my javascript tests. Also I assumed running `rake teaspoon` would already be run in the test env.
