### ISSUE TITLE
Failure running tests with rails 4 and sprockets 3 when config.expand_assets = false

### ISSUE THREAD

**Issue by liseki** [jejacks0n/teaspoon#482]
Running tests with the following setup:

```
rails 4.2.3
sprockets 3.6.0
sprockets-rails 3.0.4
```

and `config.expand_assets = false` raises a `Sprockets::Rails::Helper::AssetNotPrecompiled` error. This is because this version of rails does not take advantage of [Teaspoon's patch](https://github.com/modeset/teaspoon/blob/d9de20295dd1e9839ebeca00cc7605f8c76a0799/lib/teaspoon/engine.rb#L104-L119) of `ActionView::Helpers::AssetTagHelper#javascript_include_tag`.

Switching to `rails 4.2.5` does not raise an error however tests may fail because sprockets gives us a 'self' asset version of `spec_helper.js` which strips out any sprockets directives. See [this comment](https://github.com/modeset/teaspoon/pull/478#issuecomment-214732675) for an explanation of why this happens.

**Comment by liseki** [comment]
The simplest way to solve this (and allow other gems to easily require assets not listed for pre-compilation) is to make sprockets-rails and action view respect both the 'debug' and 'allow_non_precompiled' flags to asset tag helpers. Once that happens we won't need to make any changes to Teaspoon, and we can even do away with [Teaspoon's patch](https://github.com/modeset/teaspoon/blob/d9de20295dd1e9839ebeca00cc7605f8c76a0799/lib/teaspoon/engine.rb#L104-L119) for later versions.

As a first step I have submitted [rails/sprockets-rails#347](https://github.com/rails/sprockets-rails/pull/347). I will update here as progress is made.

**Comment by liseki** [comment]
@jejacks0n  Having those sprockets-rails and action view changes would allow us to close [rails/sprockets-rails#297](https://github.com/rails/sprockets-rails/issues/297).

**Comment by liseki** [comment]
With the advent of [sprockets-rails commit b4f9006c](https://github.com/rails/sprockets-rails/commit/b4f9006c7ff5ccd74b467c1b81e721c15dd5daf7) we have something to work with: it provides the global config option ```config.assets.check_precompiled_asset``` which defaults to true.

To firstly solve these Rails 4 issues we have to remove the [javascript_include_tag override](https://github.com/modeset/teaspoon/blob/1c634b212ec2246a0f5e7e1cacfdf6b0b4ee130a/lib/teaspoon/engine.rb#L102-L121). When ```config.expand_assets = false``` this override still sets the 'debug' option to true and as I [explained previously](https://github.com/modeset/teaspoon/pull/478#issuecomment-214732675) this makes sprockets return 'self' assets when we actually want the concatenated ones.

Secondly, we need to tell sprockets not the throw exceptions about missing assets. We have two choices:

1. Add a notice to the documentation that the developer should set ```config.assets.check_precompiled_asset = false```. Developers will probably run into exceptions at some point if they have not set this option (and have ```config.expand_assets = false```). This is a bit of an unpleasant developer experience.

2. Set ```config.assets.check_precompiled_asset = false``` within Teaspoon and have everything just work for the developer. While this is a nice developer experience it is a bit sneaky that we have set a global option for the developer's app and they may well want and expect exceptions to be thrown when  assets are called that are not declared for precompilation.

It is a bit of a shame that [rails/sprockets-rails#347](https://github.com/rails/sprockets-rails/pull/347) did not take because having a granular option would have allowed Teaspoon to solve this issue without changing the developer's app configuration. I have left my thoughts there for consideration.

So what do think @jejacks0n? How would you like to move forward with this?

**Comment by bouk** [comment]
The best fix for the pipeline stuff is maybe just to do something different depending on the sprockets version. I have a hacky patch here: https://github.com/bouk/teaspoon/commit/9dab441203c5dcbf63bc203920dfa7ba1833d90c that only sets the pipeline to debug if the sprockets version is `>= 4` and this fixes the issue of sprockets directives not working when `expand_assets = false` on master

**Comment by liseki** [comment]
@bouk what versions of sprockets and sprockets-rails are you running? And did you remember to clear your asset cache before trying the patch? I have tried it out with sprockets 3.6.0 and master sprockets-rails, and the issue is still the same with both rails 4.2.3 and 4.2.5.

**Comment by mathieujobin** [comment]
this is solved now
