### ISSUE TITLE
How to set environment of execution to 'test'

### ISSUE THREAD

**Issue by sebastianzillessen** [jejacks0n/teaspoon#495]
Hi,

for some reasons of my project architecture I would like to set the environment in which teaspoon gets executed on jenkins (from the CLI) to `test` instead of `development` unfortunately I could not find this option anywhere. 

How can I configure teaspoon to do this for all executions? (Preferable in the `teaspoon_config.rb`)

Thanks!

Sebastian

**Comment by dany-kun** [comment]
What do you think of doing `RAILS_ENV=test bundle exec teaspoon` ?

**Comment by sebastianzillessen** [comment]
Well, that would work but it would as well require, that I do this on all CI instances for all projects... 😄 Thats why I thought of a solution that I can check in into my central `teaspoon_config.rb` and then apply it automatically to all projects.

Is that somehow possible?

**Comment by jejacks0n** [comment]
It depends on how you’re running teaspoon on CI. Via the CLI I believe you can put `RAILS_ENV=test` in your env. if you’re running rake, the rails app has already been started by the time teaspoon env is executed, so… with rake, you must set the environment variable before executing rake, with the CLI you can probably put it in your `teaspoon_env.rb`.

**Comment by sebastianzillessen** [comment]
Ok, I'll give this a try.
