### ISSUE TITLE
Travis broken - and tests not running on master?

### ISSUE THREAD

**Issue by mhaylock** [jejacks0n/teaspoon#500]
When writing #499 I attempted to run the tests to verify that no tests were broken. But I was unsuccessful at getting the tests to run on master.

When I run `rake` (following the [instructions here](https://github.com/jejacks0n/teaspoon/wiki/Developing-Teaspoon) - note that `bundle exec rake` makes no difference) I get the following error from Sprockets 3.x due to the dummy app being missing a manifest.js:

```
/opt/rubies/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-rails-3.1.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
```

I checkout out the `v1.1.5` tag and found the same problem. I was able to get the tests to run on the `v1.1.4` tag (there was one failure, but that's another matter).

I can see two reasons why this may have been missed until now:
1. Travis CI is not working for this project at the moment, so any failures will be missed unless a PR is manually verified for passing specs. Right now it shows `The repository at modeset/teaspoon was not found.` which suggest Travis broke after a repo move?
2. The project does not have `Gemfile.lock` checked in so it's possible that others have a local `Gemfile.lock` that contains a combination of gems that do pass locally?

Let me know if there is anything I can do to help with this.

I haven't tried to go too deep into figuring out how to fix the tests on master - I may be able to provide assistance next week if this is needed, but I don't think fixing Travis is something I can help with - that would need to be done by someone with the correct permissions for the repo?

**Comment by mathieujobin** [comment]
tests are now running on github actions, thank you
