### ISSUE TITLE
QUnit 2

### ISSUE THREAD

**Issue by rhymes** [jejacks0n/teaspoon#503]
I'm opening this issue to see if there's interest to add QUnit 2 (or at least v1.23.1) support to teaspoon.

https://qunitjs.com/upgrade-guide-2.x/
https://github.com/jquery/qunit/blob/2.0.1/History.md

**Comment by jejacks0n** [comment]
There is. =)

**Comment by mathieujobin** [comment]
4 years and a half later... I guess not
please open a PR if you are serious about this
