### ISSUE TITLE
teaspoon-jasmine running in development environment instead of test

### ISSUE THREAD

**Issue by sujaysudheenda** [jejacks0n/teaspoon#504]
I am trying to run teaspoon tests in rails app. instead of running in test environment teaspoon is trying to run on dev environment and asks for missing database migrations.

I have specified 
`ENV['RAILS_ENV']  = 'test'` in first line of teaspoon_env.rb file
## using `gem 'teaspoon-jasmine', '~> 2.3.4'`

Error: ActiveRecord::PendingMigrationError: 

Migrations are pending. To resolve this issue, run:

```
 bin/rake db:migrate RAILS_ENV=development
```

```
gems/activerecord-4.2.7.1/lib/active_record/migration.rb:392:in `check_pending!'
gems/activerecord-4.2.7.1/lib/active_record/migration.rb:373:in `call'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:73:in `call'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
gems/railties-4.2.7.1/lib/rails/rack/logger.rb:22:in `call'
gems/request_store-1.2.1/lib/request_store/middleware.rb:8:in `call'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
51/.rvm/gems/ruby-2.2.3@global/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
51/.rvm/gems/ruby-2.2.3@global/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
51/.rvm/gems/ruby-2.2.3@global/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
51/.rvm/gems/ruby-2.2.3@global/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by jejacks0n** [comment]
rake db:test:prepare ?

---
Jeremy Jackson

**Comment by sujaysudheenda** [comment]
@jejacks0n I tried doing it before running the teaspoon tests. but it didnt seem to work. I still see the same error.

**Comment by sockmonk** [comment]
I have a similar problem: 
When I run "bin/teaspoon", logging goes to log/development.log.
When I run "RAILS_ENV=test bin/teaspoon", logging goes to log/test.log.

I doublechecked, and by default RAILS_ENV is unset, so that isn't the problem. In my Gemfile, teaspoon-jasmine is in the 'development, test' block.  
Rails 4.2.7.1, teaspoon 1.1.5, teaspoon-jasmine 2.3.4

**Comment by jejacks0n** [comment]
It's mentioned in the documentation that teaspoon by default runs in the development env. If you want to change this and not take advantage of the optimizations this provides, by all means do as you wish. Though it's not the default setup, so any issues you come across in the test env are for you to resolve.

---
Jeremy Jackson

**Comment by ameykelkar** [comment]
@sujaysudheenda 
Instead of setting environment variable as `ENV['RAILS_ENV'] = 'test'`, you could try setting the rails environment by specifying `Rails.env = 'test'` in first line of `teaspoon_env.rb`
