### ISSUE TITLE
test running failed on circle: /teaspoon route not available on circleci

### ISSUE THREAD

**Issue by phuongnd08** [jejacks0n/teaspoon#510]
Same Gemfile, same teaspoon_env.rb, on local machine, there is "/teaspoon" available. But on circleci, the path is not available.

**Comment by phuongnd08** [comment]
We use a catch all routes in our app but I guess teaspoon is supposed to deal with it.

**Comment by phuongnd08** [comment]
So ignore /teaspoon from the catchall route solve the issue for us. I guess this should be documented.

**Comment by jacksonrayhamilton** [comment]
Just ran into this myself — probably would be good to add to the docs or maybe even override (in `Rails.env.development? and `Rails.env.test?` only).

Here was my solution in case the maintainer or other bug fixers stumble upon this comment:

I changed this:

```
get "/*path" => "home#index"
```

To this:

```
if Rails.env.development? || Rails.env.test?
  get "/*path" => "home#index", constraints: ->(req) { req.fullpath !~ %r{^/teaspoon} }
else
  get "/*path" => "home#index"
end
```
