### ISSUE TITLE
Teaspoon launched via guard tries to relaunch Puma and fails due to same port conflict

### ISSUE THREAD

**Issue by ionutciordas** [jejacks0n/teaspoon#516]
Configuration:
* Rails 4.2.8
* Ruby 2.0.0-p247
* Puma 3.8.2
* Teaspoon 1.1.5
* Guard 2.14.1
* Guard-Teaspoon 0.8.0

Starting my development environment with guard starts Puma, then when the guard-teaspoon plugin starts, it tries to start Puma again and it fails due to same port conflict.

This issue started since our upgrade to Rails 4.2.

**Comment by jejacks0n** [comment]
I think guard-teaspoon is officially unsupported at this point. I don't think many people were using it, and it's hard to maintain. I'd be happy to transfer it to you, or something if you're interested in maintaining it (like 2 years later). haha
