### ISSUE TITLE
runner.rb:35:in `[]': no implicit conversion of String into Integer (TypeError)

### ISSUE THREAD

**Issue by thebravoman** [jejacks0n/teaspoon#524]
Example is just

```
console.log(1);
```
in any of the spec and it will throw this error on run without giving any more information.

```
.rvm/gems/ruby-2.2.2/gems/teaspoon-1.1.5/lib/teaspoon/runner.rb:35:in `[]': no implicit conversion of String into Integer (TypeError)
```

It was really difficult to track this down, because there was a console.log() in some of the js files and at a certain point there was a call to console.log with an integer and it was breaking without even saying a line or something.

**Comment by soccerKevin** [comment]
I have the same problem.  it happens with console.log("1") too.
if you change it from an int to a definitive string, like console.log("a1"), then it works

**Comment by jejacks0n** [comment]
interesting, hmm, wow. I think I kinda understand. I'll look into it.

**Comment by thbar** [comment]
@thebravoman thanks for the report. Indeed it was complicated to track down and I was starting to wonder if it was an incompatibility with the most recent phantomjs, for instance.

**Comment by mathieujobin** [comment]
too old and not enough info. please reopen if you can reproduce or fix.
