### ISSUE TITLE
Change port number 

### ISSUE THREAD

**Issue by sandipsubedi** [jejacks0n/teaspoon#531]
Looks like teaspoon used port 3000 by default. My assumption is coming from here : 

```
mount_at
Determines where the Teaspoon routes will be mounted. Changing this to "/jasmine" would allow you to browse to http://localhost:3000/jasmine to run your tests.

default: "/teaspoon"
```
Something else is using port 3000. Is there a way to change the port number ? If so, how can I do that ?

**Comment by jejacks0n** [comment]
https://github.com/jejacks0n/teaspoon/wiki/Teaspoon-Configuration

search for `server_port`
