### ISSUE TITLE
rake teaspoon failed

### ISSUE THREAD

**Issue by sandipsubedi** [jejacks0n/teaspoon#532]
This is my first time using this gem and I am getting following error after installing and running : 

```
rake teaspoon
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:4444/teaspoon/default
Failed to load: http://127.0.0.1:4444/teaspoon/default?reporter=Console
rake teaspoon failed
```

It does't say what the issue is. Is there a way to know what happened and how to fix it ?

Rails 4.2.8

ruby 2.4.1p111

**Comment by niltonvasques** [comment]
same problem here!

**Comment by VineethArvindFluke** [comment]
Same problem here. But with RAILS_ENV=test

**Comment by mgrsskls** [comment]
Same here. Rails 5.1.5, basic setup, no changes after installation.

**Comment by JonaMX** [comment]
Same problem but with 
Rails 4.2.10
Ruby 2.5.1

**Comment by thebravoman** [comment]
anyone found anything? Were you able to resolve this?

**Comment by mathieujobin** [comment]
not enough info and too old
