### ISSUE TITLE
rake teaspoon failed - with something connected with sqlite3 1.4.0

### ISSUE THREAD

**Issue by thebravoman** [jejacks0n/teaspoon#554]
````
rake teaspoon 
````
results in an error.

````
$ rake teaspoon
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:44769/teaspoon/default
Failed to load: http://127.0.0.1:44769/teaspoon/default?reporter=Console
rake teaspoon failed

````
This is in the log/development.log

````
WEBrick 1.3.1
ruby 2.4.5 (2018-10-18) [x86_64-linux]
Rack::Handler::WEBrick is mounted on /.
WEBrick::HTTPServer#start: pid=35705 port=43737
accept: 127.0.0.1:35276
close: 127.0.0.1:35276
accept: 127.0.0.1:35278
Rack::Handler::WEBrick is invoked.
Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
close: 127.0.0.1:35278
close TCPSocket(127.0.0.1, 43737)
going to shutdown ...
WEBrick::HTTPServer#start done.
````

sqlite3 version 1.4.0 is installed. in the gemspec file I have

````
spec.add_development_dependency "sqlite3", "~> 1.4.0"
```` 

and on bundle update I could see that this is the version used.

If I add sqlite3 version ~> 1.3.6 to the gemspec than it works

**Comment by henrywho** [comment]
Are you using bundler? Have you tried running `bundle exec rake teaspoon`?

**Comment by thebravoman** [comment]
Yes, I've tried. bundle exec rake teaspoon results in the same thing

**Comment by jejacks0n** [comment]
Ok, first, I'm not sure why you're using a gemspec. Is this a gem you're working on at the moment? Second, are you confident the site renders javascript and assets after you've updated? This really doesn't make sense as a teaspoon issue to be completely honest. Teaspoon just loads your rails server and asks for files through sprockets.
