### ISSUE TITLE
`rake teaspoon` hangs after updating to Ruby 2.5.4

### ISSUE THREAD

**Issue by rovalcor** [jejacks0n/teaspoon#559]
Running `rake teaspoon` starts the server up until the worker booting, then it hangs indefinitely without running any test. Ruby 2.5.3 works just fine for me, but 2.5.4 started showing this problem. Any ideas on where to start looking?

**Comment by jejacks0n** [comment]
It's working for me. I've updated CI to use 2.5.4, and we'll see there -- it was currently having an issue with something around selenium so I'm hoping this resolves both at the same time. 🤞
