### ISSUE TITLE
Using with Rails 6

### ISSUE THREAD

**Issue by rafamanzo** [jejacks0n/teaspoon#567]
I'm starting a fresh application using Rails 6.0.0.rc2 which I'm having trouble to configure Teaspoon to work with it.

Since I have found no specific issue regarding Rails 6 and I believe this will become a recurrent theme, I'm opening this one.

The code I have been working on can be found at https://gitlab.com/interscity/health-dashboard/internasus/tree/1-create-empty-rails-app-teaspoon

So far I have made progress by:
  * installing the master version of teaspoon instead of rubygems' one
    - this version seems to include some Rails 6 compatibility work such as https://github.com/jejacks0n/teaspoon/commit/a5f58e91de0440d7cce359f806b4432939ec2281
  * in `teaspoon_env.rb` add `app/javascript/packs` to the assets list
    - otherwise `application.js` cannot be found
  * precompile `spec_helper.js` in  `config/initializers/assets.rb`
  * following the guide on how to use RequireJS: https://github.com/jejacks0n/teaspoon/wiki/RequireJS-with-Teaspoon

Now I'm stuck on finding out how to require `require.js` for which I have no clue about its path with Rails 6. No requiring it I believe is the cause for my current error message when running `rails teaspoon`:

```
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:39643/teaspoon/default
ReferenceError: Can't find variable: require
  # application.self-d01bbf06517185239b6ee3ebf2856daf26016b313b2055280be41ff2a6f00aad.js:6 -- global code
```

Does anyone have had success with Rails 6? Thanks in advance!

**Comment by mathieujobin** [comment]
I think you need to load both from github
```ruby
gem 'teaspoon', github: 'jejacks0n/teaspoon' 
gem 'teaspoon-jasmine', github: 'jejacks0n/teaspoon' 
```

**Comment by rafamanzo** [comment]
Thanks for the suggestion.

I've tested it in this branch: https://gitlab.com/interscity/health-dashboard/internasus/tree/1-create-empty-rails-app-teaspoon-ii

But I'm still experiencing the same error and then the terminal is stuck:

```
bundle exec rails teaspoon          
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:37919/teaspoon/default
ReferenceError: Can't find variable: require
  # application.self-d01bbf06517185239b6ee3ebf2856daf26016b313b2055280be41ff2a6f00aad.js:6 -- global code
```

**Comment by mileslane** [comment]
Is there a Rails 6.0 compatible release coming soon? I am going to have to find a replacement otherwise.

**Comment by schneems** [comment]
I came to ask the same question. Looks like the last release https://rubygems.org/gems/teaspoon was from 2016.

**Comment by heitorsilva** [comment]
@schneems if you look at the releases in the repo, they're also stuck on 2016:
https://github.com/jejacks0n/teaspoon/releases

**Comment by arsduo** [comment]
I'm running into the same problem :( if any of you have recommendations for an alternative, I'd be grateful. Otherwise, if I find anything, I'll post it here.

**Comment by rafamanzo** [comment]
I gave up on teaspoon and started using jasmine standalone.

I required some work and a lot of digging to get jasmine working. If anyone is interested on how I did it you can check the MR here: https://gitlab.com/interscity/health-dashboard/internasus/-/merge_requests/70. Each commit is supposed to have more details on its description about the changes.

**Comment by mathieujobin** [comment]
Thank you @rafamanzo

**Comment by ghiculescu** [comment]
version 1.2 has been released. i assume it includes the rails 6 fixes. https://github.com/jejacks0n/teaspoon/releases

**Comment by ghiculescu** [comment]
changelog is out of date :( https://github.com/jejacks0n/teaspoon/blob/master/CHANGELOG.md

**Comment by mathieujobin** [comment]
changelog was updated and 1.2.0 presumably fully support rails 6

release will be pushed to rubygems a little later

please use latest master from github in the mean time

```
gem 'teaspoon', github: 'jejacks0n/teaspoon' 
gem 'teaspoon-jasmine', github: 'jejacks0n/teaspoon' 
```
