### ISSUE TITLE
Ruby 3.0.0

### ISSUE THREAD

**Issue by TeamNautilus** [jejacks0n/teaspoon#586]
We tried to update the **ruby** version to **3.0.0** but after the command *bundle* we received the message:

*teaspoon-1.2.0 requires ruby version ~> 2.4, which is incompatible with the current version, ruby 3.0.0p0*

we use the version **2.3.4** of **teaspoon-jasmine**. 
Any idea?

Thank you

**Comment by a2ikm** [comment]
https://github.com/jejacks0n/teaspoon/pull/583 will fix the issue.

**Comment by mathieujobin** [comment]
master branch has the ruby version unlock.
if you encounter issues and you figure them out, please open a PR 

thanks
