### ISSUE TITLE
Is teaspoon-mocha actively managed?

### ISSUE THREAD

**Issue by yuujay** [jejacks0n/teaspoon#594]
I am trying to adopt teaspoon-mocha for one of my projects, when I tried setting up mocha configurations in the `teaspoon_env` I observe that mocha `2.3.3` is the version that is considered the latest. Is my understanding right? 

My question is, will I be able to use the latest version(~8.3) of mocha that I see from npm?

**Comment by mathieujobin** [comment]
I'm afraid there are no maintainers on the mocha side
but if you are willing to open a PR with a fix. I can review, etc.

**Comment by mathieujobin** [comment]
if it works like teaspoon-jasmine, you would need to add mocha 8.3 into the teaspoon-mocha and make sure all tests pass with it

**Comment by yuujay** [comment]
Thanks for confirming. Will submit a PR / reopen this issue when some of the tests start to fail.
